### ISSUE TITLE
勝敗を複数のAIに判定させる

### ISSUE THREAD

**Issue by gotsteven** [1F10230048/resbattle-arena#59]
### 追加機能の概要

実際のディベートと同じようにOpenAI以外のAIにも判定させて多数決形式をとる

**Comment by mst-mkt** [comment]
Vercel AI SDKが対応しているAI provider
![image](https://github.com/user-attachments/assets/4fbc0468-8700-4a25-887d-0185a8095e12)
https://sdk.vercel.ai/docs/foundations/providers-and-models

**Comment by mst-mkt** [comment]
それぞれが判定だしたあとにそれをまとめるMaster的なAIが必要?
それとも数値で出させてるからそれでいい感じ™に計算することもできるか
