### ISSUE TITLE
部屋の設定を追加する

### ISSUE THREAD

**Issue by gotsteven** [1F10230048/resbattle-arena#60]
### 追加機能の概要

時間制限制と送信回数制の選択　制限時間や送信可能文字数の設定　など

**Comment by mst-mkt** [comment]
それぞれ選択可能にしてもいいけど、
そうするとUIもDBも複雑になりそうだから、いくつか選択肢(`長め | ふつう | 短め`)を選べるようにしてそれに応じていろいろな項目を変えるというのも一つの手かも

**Comment by mst-mkt** [comment]
要検討
