### ISSUE TITLE
ランダムに議題を生成する機能

### ISSUE THREAD

**Issue by gotsteven** [1F10230048/resbattle-arena#62]
### 追加機能の概要

議題に迷ったときにAIに議題を生成させられる

**Comment by mst-mkt** [comment]
AIじゃなくてもある程度こちら側で準備しておいて、そこからランダムに出すでも良さそう

**Comment by mst-mkt** [comment]
gradioのexampleみたいに、入力欄のしたにいくつか表示してそれ選べるようなイメージ

**Comment by gotsteven** [comment]
よさそう！それでいこう
